import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import { runHv, ok, err } from "../runner.js";

export function register(server: McpServer): void {
  server.tool(
    "hv_next",
    `Transition every repo in the deck to a new feature branch based on origin/<default>.
Verifies ALL repos are clean, pushed, and (if require_merged_pr is on) PRs merged before transitioning.
A branch name is auto-generated by the CLI — no need to supply one.
The local default branch is never checked out.
Note: hv_ship already auto-transitions after a successful merge — only call hv_next explicitly when you need to transition without shipping.`,
    {
      deck: z.string().describe("Deck name (e.g. 'cloud-manager'). Use hv_decks to list available decks."),
    },
    async ({ deck }) => {
      const { ok: success, output } = runHv({ op: "next", deck });

      if (!success) {
        const hint = [
          "Cannot transition — one or more repos are not ready. Next steps:",
          "1. Call hv_status to see which repos are dirty and why.",
          "2. If repos have unpushed commits or no PR → call hv_ship first.",
          "3. If an open PR is blocking (require_merged_pr: true) → merge it first.",
        ].join("\n");
        return err(output, hint);
      }

      return ok(output, "All repos transitioned to a new branch based on origin/main. Ready to start the next task — make changes and call hv_ship when done.");
    }
  );
}
