import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import { runHv, ok, err } from "../runner.js";

export function register(server: McpServer): void {
  server.tool(
    "hv_init",
    `Provision every repo in a deck and create a feature branch across all of them.
Idempotent for provisioning: missing repos are cloned, torn-down shells are restored, already-cloned repos are skipped.
A branch name is auto-generated by the CLI — no need to supply one.
For already-provisioned repos: requires all repos are on the default branch, clean, and pushed.
GitHub create-if-missing is always on — repos that don't exist on GitHub are created before cloning.`,
    {
      deck: z.string().describe("Deck name to initialize (e.g. 'cloud-manager'). Use hv_decks to list available decks."),
    },
    async ({ deck }) => {
      const { ok: success, output } = runHv({ op: "init", deck });
      if (!success) {
        const hint = [
          "Init failed. Common causes:",
          "- Repos are dirty → call hv_status to identify issues, commit and push all changes first.",
          "- Clone failed → check network access and gh CLI auth (run: gh auth status).",
          "Call hv_status to see the current state of each repo, then retry hv_init.",
        ].join("\n");
        return err(output, hint);
      }
      return ok(output, "Workspace ready. All repos are provisioned and on a new branch. Begin work — commit to this branch, then call hv_ship when ready.");
    }
  );
}
